name: Test Runner
on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: docker

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test code
        run: mvn test

